name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          npm install
          npm run build --prefix server
          npm run build --prefix client
          npm run seed 
          npm run start &
          npx wait-on http://localhost:3001
          npm run test-component

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
